### ISSUE TITLE
compilation failure with openSuSE

### ISSUE THREAD

**Issue by lemzwerg** [pts/tif22pnm#1]
While executing `./do.sh compile` I get
```
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld:
  png22pnm.o: undefined reference to symbol 'pow@@GLIBC_2.2.5'
/lib64/libm.so.6: error adding symbols: DSO missing from command line
```
[This patch](https://github.com/pts/tif22pnm/files/856325/patch.zip) fixes it for me.

**Comment by pts** [comment]
Thank you for reporting this! Fixed in 5b4fabdcf7e92c78af6daf1dda080175de0a23a2.
